"""Inital Migration

Revision ID: 30245e25c4ff
Revises: 
Create Date: 2025-06-25 14:38:32.234557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30245e25c4ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GeoJSONDataTable',
    sa.Column('fileid', sa.String(length=40), nullable=False),
    sa.Column('uploadtime', sa.String(length=30), nullable=True),
    sa.Column('updatetime', sa.String(length=30), nullable=True),
    sa.Column('notifytime', sa.String(length=30), nullable=True),
    sa.Column('logger', sa.String(length=80), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('soundings', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('messages', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('fileid')
    )
    op.create_table('WIBLDataTable',
    sa.Column('fileid', sa.String(length=40), nullable=False),
    sa.Column('processtime', sa.String(length=30), nullable=True),
    sa.Column('updatetime', sa.String(length=30), nullable=True),
    sa.Column('notifytime', sa.String(length=30), nullable=True),
    sa.Column('logger', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=True),
    sa.Column('soundings', sa.Integer(), nullable=True),
    sa.Column('starttime', sa.String(length=30), nullable=True),
    sa.Column('endtime', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('messages', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('fileid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WIBLDataTable')
    op.drop_table('GeoJSONDataTable')
    # ### end Alembic commands ###
