"""

Revision ID: 4313c179af8f
Revises: 8fce3ccf5be7
Create Date: 2025-07-16 09:59:10.250836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '4313c179af8f'
down_revision: Union[str, Sequence[str], None] = '8fce3ccf5be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('WIBLDataTable', sa.Column('boundingbox', Geometry(geometry_type='POLYGON', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_geospatial_index('idx_WIBLDataTable_boundingbox', 'WIBLDataTable', ['boundingbox'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_column('WIBLDataTable', 'depthtotal')
    op.drop_column('WIBLDataTable', 'boundinglon')
    op.drop_column('WIBLDataTable', 'boundinglat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WIBLDataTable', sa.Column('boundinglat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('WIBLDataTable', sa.Column('boundinglon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('WIBLDataTable', sa.Column('depthtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_geospatial_index('idx_WIBLDataTable_boudingbox', table_name='WIBLDataTable', postgresql_using='gist', column_name='boudingbox')
    op.drop_geospatial_column('WIBLDataTable', 'boudingbox')
    # ### end Alembic commands ###
