"""

Revision ID: 45d180746fa0
Revises: 6b48fb173ebe
Create Date: 2025-07-02 11:40:06.201591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d180746fa0'
down_revision: Union[str, Sequence[str], None] = 'b8eeadd45a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('GeoJSONDataTable', 'uploadtime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('GeoJSONDataTable', 'updatetime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('GeoJSONDataTable', 'notifytime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'processtime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'updatetime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'notifytime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'starttime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'endtime',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WIBLDataTable', 'endtime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'starttime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'notifytime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'updatetime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('WIBLDataTable', 'processtime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('GeoJSONDataTable', 'notifytime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('GeoJSONDataTable', 'updatetime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('GeoJSONDataTable', 'uploadtime',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
