"""

Revision ID: 8fce3ccf5be7
Revises: a163472b2996
Create Date: 2025-07-10 18:32:24.753882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fce3ccf5be7'
down_revision: Union[str, Sequence[str], None] = 'a163472b2996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WIBLDataTable', sa.Column('depthtotal', sa.Float(), nullable=True))
    op.drop_column('WIBLDataTable', 'totaldepth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WIBLDataTable', sa.Column('totaldepth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('WIBLDataTable', 'depthtotal')
    # ### end Alembic commands ###
