"""

Revision ID: a163472b2996
Revises: dbde4f401828
Create Date: 2025-07-10 18:26:47.288524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a163472b2996'
down_revision: Union[str, Sequence[str], None] = 'dbde4f401828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WIBLDataTable', sa.Column('totaldepth', sa.Float(), nullable=True))
    op.add_column('WIBLDataTable', sa.Column('boundinglat', sa.Float(), nullable=True))
    op.add_column('WIBLDataTable', sa.Column('boundinglon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WIBLDataTable', 'boundinglon')
    op.drop_column('WIBLDataTable', 'boundinglat')
    op.drop_column('WIBLDataTable', 'totaldepth')
    # ### end Alembic commands ###
