FROM python:3.12-slim-bookworm

WORKDIR /var/local/wibl/frontend
ADD ./src /var/local/wibl/frontend

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install -r requirements.txt
