include:
  - ../wibl-manager/docker-compose.yaml

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - manager
    restart: always
    env_file:
      - frontend.env
    environment:
      FRONTEND_DATABASE_URI: ${FRONTEND_DATABASE_URI}
      MANAGEMENT_URL: 'http://manager:5000'
      MANAGEMENT_HEARTBEAT_PATH: '/heartbeat'
    ports:
      - '8000:8000'
    volumes:
      - 'dbdata_fe:/var/wibl'
        #- './file_upload:/var/wibl'
        #- 'dbdata:/var/wibl/database.db'
        #- 'dbdata:/var/wibl'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/heartbeat"]
      interval: 10s
      timeout: 1s
      retries: 5
    command: 'gunicorn wibl_frontend.application:app --workers 1 --timeout 50 --bind 0.0.0.0:8000 --access-logfile -'
  localstack:
    image: localstack/localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,lambda,sns, kinesis, list-streams
      - DEBUG=0
      - LS_LOG=error
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  dbdata_fe:
          #dbdata:
