FROM python:3.12-slim-bookworm

WORKDIR /var/local/wibl/frontend
ADD ./src /var/local/wibl/frontend

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt update && apt install -y nodejs npm && rm -rf /var/lib/apt/lists/*
RUN npm install ol --prefix /var/local/wibl/frontend/static


COPY requirements.txt ./
RUN pip install -r requirements.txt
