services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - manager.env
    ports:
      #- '8001:8000'
      - '6080:5000'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/heartbeat"]
      interval: 30s
      timeout: 1s
      retries: 5
    command: 'uvicorn src.wibl_manager.application:app --host 0.0.0.0 --port 5000 --workers 1'
    develop:
      watch:
        - action: sync+restart
          path: ./src/wibl_manager
          target: /usr/src/wibl/wibl_manager
    depends_on:
      db:
        condition: service_healthy
        restart: true
  localstack:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=us-east2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DEBUG=0
      - LS_LOG=error
    ports:
      - "14566:4566"
      - "14510-14559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./src/wibl_manager/tests/047EEFC3-7EEC-4FFD-816F-B6DB15E52297.geojson:/opt/code/localstack/047EEFC3-7EEC-4FFD-816F-B6DB15E52297.geojson"
      - "./scripts/s3-test-load.sh:/etc/localstack/init/ready.d/s3-test-load.sh"
  db:
    image: postgres:17-bookworm
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    command: -p 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
