version: '3'

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - manager.env
    environment:
      MANAGER_DATABASE_URI: 'sqlite:////var/wibl/database.db'
    ports:
      #- '8001:8000'
      - '5000:5000'
    volumes:
      - 'dbdata_mgr:/var/wibl'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/heartbeat"]
      interval: 10s
      timeout: 1s
      retries: 5
    command: 'gunicorn wibl_manager.application:app --workers 1 --bind 0.0.0.0:5000 --access-logfile -'
volumes:
  dbdata_mgr:
