
FROM --platform=linux/arm64 python:3.11-slim AS builder

WORKDIR /usr/src/wibl
ADD ./ /usr/src/wibl

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install postgres command tools,
# so the manager knows when the database is ready
RUN apt-get update -y \
    && apt-get install -y curl postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install curl so that our healthcheck works under Docker
RUN apt-get install -y curl

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install '.[server]'

FROM builder as final

EXPOSE 5000

COPY entrypoint.sh /usr/src/wibl/entrypoint.sh
RUN chmod +x /usr/src/wibl/entrypoint.sh

ENTRYPOINT ["/usr/src/wibl/entrypoint.sh"]

